### ISSUE TITLE
suggestion: change the color

### ISSUE THREAD

**Issue by Jawaliya123** [Parth731/github-crash-course#2]
I think it looks better if main title is a bit more orange.

styling rule could be changed like this 

```css
h1 {
  color: #efa82e;
}
```
